-- ============================================================
-- WebsiteMo CMS — Supabase PostgreSQL Database Schema
-- Run this script inside your Supabase SQL Editor:
-- https://app.supabase.com/project/_/sql
-- ============================================================

-- Enable UUID extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        TEXT NOT NULL UNIQUE,
    email           TEXT NOT NULL UNIQUE,
    password_hash   TEXT NOT NULL,
    display_name    TEXT NOT NULL DEFAULT '',
    role            TEXT NOT NULL DEFAULT 'subscriber',
    status          TEXT NOT NULL DEFAULT 'active',
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- 2. USER META TABLE
CREATE TABLE IF NOT EXISTS public.user_meta (
    meta_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    meta_key    TEXT NOT NULL,
    meta_value  TEXT
);
CREATE INDEX IF NOT EXISTS idx_usermeta_user ON public.user_meta(user_id);
CREATE INDEX IF NOT EXISTS idx_usermeta_key ON public.user_meta(meta_key);

-- 3. POSTS TABLE (posts, pages, attachments, revisions)
CREATE TABLE IF NOT EXISTS public.posts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id       BIGINT NOT NULL REFERENCES public.users(id),
    post_type       TEXT NOT NULL DEFAULT 'post',
    post_status     TEXT NOT NULL DEFAULT 'draft',
    title           TEXT NOT NULL DEFAULT '',
    slug            TEXT NOT NULL DEFAULT '',
    content         TEXT NOT NULL DEFAULT '',
    excerpt         TEXT NOT NULL DEFAULT '',
    password        TEXT DEFAULT '',
    parent_id       BIGINT DEFAULT 0,
    menu_order      INT DEFAULT 0,
    comment_status  TEXT NOT NULL DEFAULT 'open',
    ping_status     TEXT NOT NULL DEFAULT 'open',
    mime_type       TEXT DEFAULT '',
    guid            TEXT DEFAULT '',
    publish_date    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_posts_type_status ON public.posts(post_type, post_status);
CREATE INDEX IF NOT EXISTS idx_posts_author ON public.posts(author_id);
CREATE INDEX IF NOT EXISTS idx_posts_slug ON public.posts(slug);

-- 4. POST META TABLE
CREATE TABLE IF NOT EXISTS public.post_meta (
    meta_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    meta_key    TEXT NOT NULL,
    meta_value  TEXT
);
CREATE INDEX IF NOT EXISTS idx_postmeta_post ON public.post_meta(post_id);
CREATE INDEX IF NOT EXISTS idx_postmeta_key ON public.post_meta(meta_key);

-- 5. TERMS & TAXONOMIES
CREATE TABLE IF NOT EXISTS public.terms (
    term_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    slug        TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.term_taxonomy (
    term_taxonomy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term_id          BIGINT NOT NULL REFERENCES public.terms(term_id) ON DELETE CASCADE,
    taxonomy         TEXT NOT NULL DEFAULT 'category',
    description      TEXT DEFAULT '',
    parent           BIGINT DEFAULT 0,
    count            BIGINT DEFAULT 0,
    UNIQUE(term_id, taxonomy)
);

CREATE TABLE IF NOT EXISTS public.term_relationships (
    object_id        BIGINT NOT NULL,
    term_taxonomy_id BIGINT NOT NULL REFERENCES public.term_taxonomy(term_taxonomy_id) ON DELETE CASCADE,
    term_order       INT DEFAULT 0,
    PRIMARY KEY (object_id, term_taxonomy_id)
);

-- 6. COMMENTS TABLE
CREATE TABLE IF NOT EXISTS public.comments (
    comment_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id         BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    user_id         BIGINT DEFAULT 0,
    author_name     TEXT NOT NULL DEFAULT '',
    author_email    TEXT NOT NULL DEFAULT '',
    author_url      TEXT DEFAULT '',
    author_ip       TEXT DEFAULT '',
    content         TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'pending',
    parent_id       BIGINT DEFAULT 0,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.comment_meta (
    meta_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id  BIGINT NOT NULL REFERENCES public.comments(comment_id) ON DELETE CASCADE,
    meta_key    TEXT NOT NULL,
    meta_value  TEXT
);

-- 7. OPTIONS TABLE (Key-Value site settings)
CREATE TABLE IF NOT EXISTS public.options (
    option_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_name  TEXT NOT NULL UNIQUE,
    option_value TEXT NOT NULL DEFAULT '',
    autoload     TEXT NOT NULL DEFAULT 'yes'
);

-- DEFAULT OPTIONS SEED
INSERT INTO public.options (option_name, option_value, autoload) VALUES
('site_title', 'WebsiteMo', 'yes'),
('site_tagline', 'Build Your Identity | Custom Website Agency', 'yes'),
('admin_email', 'admin@websitemo.com', 'yes'),
('users_can_register', '0', 'yes'),
('default_role', 'subscriber', 'yes'),
('permalink_structure', '/%postname%/', 'yes'),
('active_plugins', '["akismet-antispam", "gutenberg-blocks-plus", "seo-optimizer-pro"]', 'yes')
ON CONFLICT (option_name) DO NOTHING;
